apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-sample-kustomize
  namespace: test-lee
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: unimin
  url: https://gitlab.com/unimin/k8s-sample-kustomize
