apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-kustomize
  namespace: test-lee
spec:
  interval: 5m
  retryInterval: 2m0s
  path: ./overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-sample-kustomize
    namespace: test-lee
  targetNamespace: test-lee
