apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-helm
  namespace: test-lee
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: sample-helm
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-sample-helm
      interval: 5m
  releaseName: sample-helm
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
